# Generated by Django 2.1.5 on 2019-01-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='nome',
            new_name='name',
        ),
    ]
