# Generated by Django 2.1.5 on 2019-01-30 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('core', '0002_remove_pontoturistico_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
            preserve_default=False,
        ),
    ]
