# Generated by Django 2.1.5 on 2019-01-31 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pontoturistico_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
    ]
