# Generated by Django 2.1.5 on 2019-01-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracao',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='atracao',
            name='min_age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='atracao',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='atracao',
            name='opening_hours',
            field=models.CharField(default='', max_length=150),
        ),
    ]
