# Generated by Django 2.1.5 on 2019-01-30 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_auto_20190130_1606'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atracao',
            new_name='Recurso',
        ),
    ]
